name: Build & deploy master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '18'
          cache: 'npm'
      - name: Download dependencies
        run: npm ci
      - name: Build
        run: npm run build:production
      - name: Deploy to AWS
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          tar -czf pfcalc.tar.gz -C ./dist/frontend .
          ssh -i key.pem ec2-user@${{ secrets.AWS_HOST }} sudo rm -rf /usr/share/nginx/html/*
          scp -i key.pem pfcalc.tar.gz ec2-user@${{ secrets.AWS_HOST }}:/home/ec2-user/pfcalc.tar.gz
          ssh -i key.pem ec2-user@${{ secrets.AWS_HOST }} sudo tar -xzf ./pfcalc.tar.gz -C /usr/share/nginx/html/
